log_interval: 1

log_params_norm: True
log_num_zeros_in_grad: True
log_throughput: False
log_progress: False

timing_log_level: 0
timing_log_option: minmax
tensorboard_log_interval: 1
tensorboard_queue_size: 1000

# content
log_timers_to_tensorboard: False
log_batch_size_to_tensorboard: False
log_learning_rate_to_tensorboard: True
log_learning_rate_to_tensorboard: True
log_validation_ppl_to_tensorboard: False
log_memory_to_tensorboard: False
log_world_size_to_tensorboard: False
log_loss_scale_to_tensorboard: True

wandb_project: ''
wandb_exp_name: ''
wandb_save_dir: ''

enable_one_logger: True
one_logger_async: false
one_logger_project: megatron-lm
one_logger_run_name: null

tensorboard_dir: null

