# lr schedule
lr: null
min_lr: 0.0

head_lr_mult: 1.0
decoupled_lr: null
decoupled_min_lr: null

# warmup 
lr_warmup_iters: null
lr_warmup_init: 0.0
lr_warmup_fraction: null
lr_warmup_samples: null

# decay
lr_decay_style: cosine
lr_decay_iters: null
lr_decay_samples: null

lr_wsd_decay_style: exponential
lr_wsd_decay_iters: null
lr_wsd_decay_samples: null