model_parallel_size: null
tensor_model_parallel_size: null
context_parallel_size: 1
pipeline_model_parallel_size: 1
virtual_pipeline_model_parallel_size: null
sequence_parallel: false # True
expert_model_parallel_size: 1
use_tp_pp_dp_mapping: false
num_layers_per_virtual_pipeline_stage: null
data_parallel_size: null