__inherit__: llama-base.yaml

num_layers: 60
hidden_size: 6656
ffn_hidden_size: 17920
num_attention_heads: 52
group_query_attention: false
norm_epsilon: 1.0e-06

max_position_embeddings: 2048
rotary_base: 10000
make_vocab_size_divisible_by: 100
vocab_size: 32000